sudo: false

language: scala
scala:
  - 2.12.4
  - 2.11.11
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm


script: sbt ++$TRAVIS_SCALA_VERSION test

branches:
  only:
  - master
  - develop
